import {
  Gear,
  MagnifyingGlass,
  CaretDown,
  CaretRight,
  MagnifyingGlassPlus,
  MagnifyingGlassMinus,
  Star,
  Terminal,
  Code,
  Command,
  Moon,
  Sun,
  Sidebar,
  XSquare,
  SquaresFour,
  CircleDashed,
  Trash,
  Eye,
  EyeSlash,
  PencilSimple,
  Lock,
  LockOpen,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowsClockwise,
  ArrowBendUpRight,
  Square,
  Scribble,
  Link as PhosphorLink,
  LinkBreak as PhosphorUnlink,
  ArrowRight as PhosphorArrowRight,
  X as PhosphorX
} from "@phosphor-icons/react";

export {
  Gear,
  MagnifyingGlass as Search,
  CaretDown as ChevronDown,
  CaretRight as ChevronRight,
  MagnifyingGlassPlus as ZoomIn,
  MagnifyingGlassMinus as ZoomOut,
  Star,
  Terminal,
  Code as FileCode,
  Command,
  Moon,
  Sun,
  Sidebar as PanelLeft,
  Sidebar as PanelRight,
  XSquare as PanelLeftClose,
  XSquare as PanelRightClose,
  SquaresFour as Grid,
  CircleDashed as Circle,
  Trash,
  Eye,
  EyeSlash as EyeOff,
  PencilSimple as Pencil,
  Lock,
  LockOpen,
  ArrowClockwise as RotateRight,
  ArrowCounterClockwise as RotateLeft,
  ArrowsClockwise as Repeat,
  ArrowBendUpRight as ArrowBendDoubleUpRight,
  Square,
  Scribble,
  PhosphorLink as Link,
  PhosphorUnlink as Unlink,
  PhosphorArrowRight as ArrowRight,
  PhosphorX as X
};